### ISSUE TITLE
Are you using this backup method?

### ISSUE THREAD

**Issue by popstas** [osiell/ansible-rsnapshot-slave#3]
Hello, I see that role don't updates for 2 years. You found better backup system or this role work fine?

**Comment by sebalix** [comment]
We are using it with https://github.com/osiell/ansible-rsnapshot-master/ without any trouble (from Debian Squeeze to Jessie, and I will test it on Stretch soon).
Maybe I will merge these two roles in one in the future to make things simpler.

**Comment by popstas** [comment]
Thanks.
